tap "oven-sh/bun", trusted: true
tap "tw93/tap", trusted: true
brew "aliyun-cli"
brew "bash"
brew "bat"
brew "freetype"
brew "ccusage"
brew "eza"
brew "fd"
brew "fish"
brew "fnm"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "helix"
brew "herdr"
brew "lazygit"
brew "macmon"
brew "mas"
brew "maven"
brew "mole"
brew "node"
brew "openjdk@17"
brew "pnpm"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "uv"
brew "yazi"
brew "zoxide"
brew "oven-sh/bun/bun", trusted: true
cask "chatgpt"
cask "claude"
cask "claude-code@latest"
cask "codex"
cask "flowvision"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "iina"
cask "keepingyouawake"
cask "keka"
cask "notion"
cask "obsidian"
cask "orbstack"
cask "pearcleaner"
cask "raycast"
cask "shottr"
cask "typora"
cask "upscayl"
cask "visual-studio-code"
cask "zed"
mas "BaiduNetdisk", id: 547166701
mas "Feishu", id: 1551632588
mas "NetEaseMusic", id: 944848654
mas "QQ", id: 451108668
mas "TencentMeeting", id: 1484048379
mas "WeChat", id: 836500024
mas "WPS Office", id: 1443749478
npm "@larksuite/cli"
