tap "oven-sh/bun", trusted: true
tap "tw93/tap", trusted: true
brew "bash"
brew "bat"
brew "btop"
brew "freetype"
brew "cloc"
brew "dua-cli"
brew "eza"
brew "fd"
brew "fish"
brew "fisher"
brew "fnm"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "jq"
brew "lazygit"
brew "macmon"
brew "mas"
brew "maven"
brew "mole"
brew "neovim"
brew "node"
brew "openjdk@17"
brew "pnpm"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "uv"
brew "yazi"
brew "zoxide"
brew "oven-sh/bun/bun", trusted: true
cask "betterdisplay"
cask "cc-switch"
cask "chatgpt"
cask "clash-verge-rev"
cask "claude-code@latest"
cask "codex"
cask "easydict"
cask "flowvision"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-lxgw-wenkai"
cask "font-meslo-lg-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "iina"
cask "keka"
cask "notion"
cask "obsidian"
cask "open-design"
cask "orbstack"
cask "otty"
cask "pearcleaner"
cask "raycast"
cask "sf-symbols"
cask "shottr"
cask "typora"
cask "upscayl"
cask "visual-studio-code"
cask "zed"
mas "Amphetamine", id: 937984704
mas "QQ", id: 451108668
mas "WPS Office", id: 1443749478
mas "剪映专业版", id: 1529999940
mas "微信", id: 836500024
mas "百度网盘", id: 547166701
mas "网易云音乐", id: 944848654
mas "腾讯会议", id: 1484048379
mas "飞书", id: 1551632588
