# ── File Manager ──────────────────────────────────────────────────────

[mgr]
ratio = [2, 2, 3]
show_hidden = true
mouse_events = ["click", "scroll"]

# ── Preview ──────────────────────────────────────────────────────────

[preview]
max_width = 2048
max_height = 2048
image_quality = 85

# ── Git ───────────────────────────────────────────────────────────────

[[plugin.prepend_fetchers]]
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
url = "*/"
run = "git"
group = "git"
