git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --features="everforest-dark" --syntax-theme="gruvbox-dark"
      useConfig: false

gui:
  theme:
    activeBorderColor:
      - "#a7c080"
      - bold

    inactiveBorderColor:
      - "#475258"

    searchingActiveBorderColor:
      - "#dbbc7f"
      - bold

    optionsTextColor:
      - "#83c092"

    selectedLineBgColor:
      - "#3a464c"

    inactiveViewSelectedLineBgColor:
      - "#343f44"

    cherryPickedCommitFgColor:
      - "#2d353b"

    cherryPickedCommitBgColor:
      - "#dbbc7f"

    markedBaseCommitFgColor:
      - "#2d353b"

    markedBaseCommitBgColor:
      - "#83c092"

    unstagedChangesColor:
      - "#e67e80"

    defaultFgColor:
      - "#d3c6aa"
