# Homebrew Configuration
export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"

export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=0
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_ENV_HINTS=0
export HOMEBREW_MAKE_JOBS=$(sysctl -n hw.logicalcpu)

if [ -x /opt/homebrew/bin/brew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Environment Variables
export EDITOR=nvim

# Conda
export CONDA_ROOT="/opt/homebrew/Caskroom/miniforge/base"

# PATH Configuration
typeset -U path
path=(
  "/opt/homebrew/opt/make/libexec/gnubin"
  "/usr/local/share/dotnet"
  "$HOME/Library/Application Support/JetBrains/Toolbox/scripts"
  "$HOME/.lmstudio/bin"
  "/opt/homebrew/opt/openjdk/bin"
  "/opt/homebrew/opt/llvm/bin"
  "$HOME/.antigravity/antigravity/bin"
  "$CONDA_ROOT/bin"
  $path
)

# OrbStack
source ~/.orbstack/shell/init.zsh 2>/dev/null || :