# Zsh Caching & History Setup
[[ -d "$HOME/.cache/zsh" ]] || mkdir -p "$HOME/.cache/zsh"
export ZSH_COMPDUMP="$HOME/.cache/zsh/zcompdump"
export HISTFILE="$HOME/.cache/zsh/history"

# Homebrew
if command -v brew >/dev/null; then
  fpath=($(brew --prefix)/share/zsh-completions $fpath)
fi

# Oh-my-zsh
export ZSH_DISABLE_COMPFIX="true"
export ZSH="$HOME/.config/oh-my-zsh"
plugins=(
  git
  zoxide
)
source "$ZSH/oh-my-zsh.sh"

# zsh-autosuggestions
source "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
# zsh-history-substring-search
source "$(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh"
# zsh-syntax-highlighting
source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# Starship
if command -v starship &>/dev/null; then
    eval "$(starship init zsh)"
fi

# Fzf
__fzf_loaded=0
_fzf_load() {
  if [[ $__fzf_loaded -eq 0 ]]; then
    source <(fzf --zsh)
    __fzf_loaded=1
  fi
}
fzf() {
  _fzf_load
  command fzf "$@"
}

# Alias
alias c='clear'
alias s='exec zsh -l'
alias el='eza --long --header --icons --git --all'
alias et='eza --tree --level=2 --long --header --icons --git'
alias ip='ipconfig getifaddr en0'
alias ports='lsof -i -P | grep -i "listen"'
alias disk='smartctl -a disk3'
alias df='df -h'
alias py='python'
alias f='fastfetch'
alias lg='lazygit'

alias bu='brew update && brew upgrade && brew upgrade --cask && brew cleanup --prune=all'
alias bc='brew cleanup --prune=all && brew autoremove'
alias bi='brew install'
alias bri='brew reinstall'
alias bl='brew list'
alias bui='brew uninstall --zap'
alias bs='brew search'
alias bd='brew deps --installed --tree'

alias ts='tmux source-file ~/.config/tmux/tmux.conf'
alias tls='tmux ls'
alias ta='tmux attach'
alias tn='tmux new -s'
alias tk='tmux kill-session -t'

alias fzf="fzf --style full --preview 'fzf-preview.sh {}' --bind 'focus:transform-header:file --brief {}'"
alias fzd='cd $(find * -type d | fzf)'
alias fzh="history | fzf"
alias vzf='nvim $(fzf)'
alias fzb='git branch | fzf | xargs git checkout'
alias fzp='ps aux | fzf'

alias cel='conda env list'
alias ci='conda install'
alias cui='conda remove'
alias cu='conda update --all'
alias cs='conda search'
alias cl='conda list'
alias cc='conda clean --all -y'
alias ca='conda activate'
alias cde='conda deactivate'

alias gs='git status'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'
alias gpl='git pull'
alias gd='git diff'

# Yazi
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}

# Zoxide
cd() {
  if [[ $# -eq 0 ]]; then
    builtin cd ~
    return
  fi

  if [[ -d "$1" || "$1" == -* ]]; then
    builtin cd "$@"
    return
  fi

  z "$@"
}
