# Zsh Caching & History Setup
[[ -d "$HOME/.cache/zsh" ]] || mkdir -p "$HOME/.cache/zsh"
export ZSH_COMPDUMP="$HOME/.cache/zsh/zcompdump"
export HISTFILE="$HOME/.cache/zsh/history"
export HISTSIZE=10000
export SAVEHIST=10000

# Plugins
if [[ -d "/opt/homebrew/share/zsh-completions" ]]; then
  fpath=(/opt/homebrew/share/zsh-completions $fpath)
fi

BREW_PREFIX=$(brew --prefix)

[[ -f "$BREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh" ]] && source "$BREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
[[ -f "$BREW_PREFIX/share/zsh-history-substring-search/zsh-history-substring-search.zsh" ]] && source "$BREW_PREFIX/share/zsh-history-substring-search/zsh-history-substring-search.zsh"
[[ -f "$BREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]] && source "$BREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# Starship
if command -v starship &>/dev/null; then
    eval "$(starship init zsh)"
fi

# FZF
if command -v fzf >/dev/null; then
  source <(fzf --zsh)
fi

# Alias
alias c='clear'
alias s='exec zsh -l'
alias el='eza --long --header --icons --git --all'
alias et='eza --tree --level=2 --long --header --icons --git'
alias ip='ipconfig getifaddr en0'
alias ports='lsof -i -P | grep -i "listen"'
alias disk='smartctl -a disk3'
alias df='df -h'
alias py='python'
alias lg='lazygit'
alias mf='musicfox'
alias xcode-clt='sudo xcode-select -s /Library/Developer/CommandLineTools'
alias xcode-app='sudo xcode-select -s /Applications/Xcode.app/Contents/Developer'

alias bu='brew update && brew upgrade && brew upgrade --cask'
alias bc='brew autoremove && brew cleanup --prune=all'
alias bi='brew install'
alias bri='brew reinstall'
alias bl='brew leaves && brew list --cask'
alias bui='brew uninstall --zap'
alias bs='brew search'
alias bd='brew deps --installed --tree'
alias bif='brew info'

alias ts='tmux source-file ~/.config/tmux/tmux.conf'
alias tls='tmux ls'
alias ta='tmux attach'
alias tn='tmux new -s'
alias tk='tmux kill-session -t'

alias fzf='fzf \
  --style full \
  --preview "fzf-preview.sh {}" \
  --bind "focus:transform-header:file --brief {}"'
alias fzd='cd $(find * -type d | fzf)'
alias fzh="history | fzf"
alias vzf='nvim $(fzf)'
alias fzb='git branch | fzf | xargs git checkout'
alias fzp='ps aux | fzf'

alias cel='conda env list'
alias ci='conda install'
alias cui='conda remove'
alias cu='conda update --all'
alias cs='conda search'
alias cl='conda list'
alias cc='conda clean --all -y'
alias ca='conda activate'
alias cde='conda deactivate'

alias gs='git status'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'
alias gpl='git pull'
alias gd='git diff'

# Yazi
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}

# Zoxide
if command -v zoxide &>/dev/null; then
  eval "$(zoxide init zsh --cmd cd)"
fi

# Compinit
autoload -Uz compinit
_compinit_once() {
  unfunction _compinit_once
  compinit -C -d "$ZSH_COMPDUMP"
}
zle -N complete-word _compinit_once

# Conda
__load_conda() {
  unset -f conda
  unset -f __load_conda

  if [[ -f "$CONDA_ROOT/etc/profile.d/conda.sh" ]]; then
    source "$CONDA_ROOT/etc/profile.d/conda.sh"
  else
    echo "conda.sh not found"
    return 1
  fi
}

conda() {
  __load_conda
  conda "$@"
}

lazygit-widget() {
  lazygit
  zle reset-prompt
}
zle -N lazygit-widget
bindkey '^g' lazygit-widget
